// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "alienwade007@gmail.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://github.com/MartinHeinz/go-project-blueprint/blob/master/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/brand/deleteBrand": {
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "brand"
                ],
                "summary": "DeleteBrand",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search by brandId",
                        "name": "brandId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "$ref": "#/definitions/adapter.NonDataResp"
                        }
                    }
                }
            }
        },
        "/api/brand/findAllBrand": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "brand"
                ],
                "summary": "取得所有品牌",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search by createAfter",
                        "name": "createAfter",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by createBefore",
                        "name": "createBefore",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by size",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by sort",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "search by order",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/adapter.DataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/services.BrandDto"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/brand/findBrand": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "brand"
                ],
                "summary": "取得品牌",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search by brandId",
                        "name": "brandId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/adapter.DataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/services.BrandDto"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/brand/postBrand": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "brand"
                ],
                "summary": "刊登品牌",
                "parameters": [
                    {
                        "description": "建立品牌",
                        "name": "PostBrand",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services.PostBrandDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/adapter.DataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/services.BrandDto"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/brand/updateBrand": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "brand"
                ],
                "summary": "更新品牌",
                "parameters": [
                    {
                        "description": "編輯品牌",
                        "name": "PostBrand",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services.UpdateBrandDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "$ref": "#/definitions/adapter.NonDataResp"
                        }
                    }
                }
            }
        },
        "/api/collection/findAllCollection": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collection"
                ],
                "summary": "取得所有蒐藏",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search by owner",
                        "name": "owner",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by creationId",
                        "name": "creationId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by size",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by sort",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "search by order",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/adapter.DataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/services.CollectDto"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/collection/findCollection": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collection"
                ],
                "summary": "取得蒐藏",
                "parameters": [
                    {
                        "type": "string",
                        "description": "owner",
                        "name": "owner",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "creationId",
                        "name": "creationId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/adapter.DataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/services.CollectDto"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/creation/deleteCreation": {
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "creation"
                ],
                "summary": "刪除藝術品",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search by id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "$ref": "#/definitions/adapter.NonDataResp"
                        }
                    }
                }
            }
        },
        "/api/creation/findAllCreation": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "creation"
                ],
                "summary": "取得所有藝術品資訊",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search by page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by size",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by creationIds",
                        "name": "creationIds",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by properties",
                        "name": "properties",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by saleStartBefore",
                        "name": "saleStartBefore",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by saleStartAfter",
                        "name": "saleStartAfter",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "search by maxPrice",
                        "name": "maxPrice",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "search by minPrice",
                        "name": "minPrice",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by creationName",
                        "name": "creationName",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by creator",
                        "name": "creator",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by brandId",
                        "name": "brandId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by sort",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "search by order",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/adapter.DataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/services.CreationDto"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/creation/findCreation": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "creation"
                ],
                "summary": "取得藝術品資訊",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search by creationId",
                        "name": "creationId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/adapter.DataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/services.CreationDto"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/creation/postCreation": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "creation"
                ],
                "summary": "刊登藝術品",
                "parameters": [
                    {
                        "description": "藝術品資料",
                        "name": "postCreation",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services.PostCreationDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/adapter.DataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/services.CreationDto"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/creation/updateCreation": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "creation"
                ],
                "summary": "更新藝術品",
                "parameters": [
                    {
                        "description": "編輯藝術品",
                        "name": "postCreation",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services.UpdateCreationDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "$ref": "#/definitions/adapter.NonDataResp"
                        }
                    }
                }
            }
        },
        "/api/item/deliverItem": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "item"
                ],
                "summary": "商品交貨",
                "parameters": [
                    {
                        "description": "刊登房屋物件",
                        "name": "DeliverItemDto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services.DeliverItemDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/adapter.DataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/services.ItemDto"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/item/findAllItem": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "item"
                ],
                "summary": "取得所有商品資訊",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search by owner",
                        "name": "owner",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by brandOwner",
                        "name": "brandOwner",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by size",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by sort",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "search by order",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/adapter.DataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/services.ItemDto"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/item/getAmountOfItem": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "item"
                ],
                "summary": "取得商品總量",
                "parameters": [
                    {
                        "type": "string",
                        "description": "brandId",
                        "name": "brandId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/adapter.DataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/item/orderItem": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "item"
                ],
                "summary": "商品訂貨",
                "parameters": [
                    {
                        "description": "商品訂購資料",
                        "name": "OrderItemDto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services.OrderItemDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "$ref": "#/definitions/adapter.NonDataResp"
                        }
                    }
                }
            }
        },
        "/api/item/{contract}/{token}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "item"
                ],
                "summary": "取得商品資訊",
                "parameters": [
                    {
                        "type": "string",
                        "description": "contract",
                        "name": "contract",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/adapter.DataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/services.ItemDto"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/stock/findAllStock": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stock"
                ],
                "summary": "取得所有庫存",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search by page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by size",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by creationId",
                        "name": "creationId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by brandId",
                        "name": "brandId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/adapter.DataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/services.CollectDto"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/trade/findAllTransaction": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trade"
                ],
                "summary": "取得所有交易資訊",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search by page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by size",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by properties",
                        "name": "properties",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by tradedBefore",
                        "name": "tradedBefore",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by tradedAfter",
                        "name": "tradedAfter",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "search by maxPrice",
                        "name": "maxPrice",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "search by minPrice",
                        "name": "minPrice",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by properties",
                        "name": "properties",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by creationName",
                        "name": "creationName",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by creationId",
                        "name": "creationId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by brandId",
                        "name": "brandId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by buyer",
                        "name": "buyer",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by seller",
                        "name": "seller",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by sort",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "search by order",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/adapter.DataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/services.TransactionDto"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/trade/findTransaction": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trade"
                ],
                "summary": "取得交易資訊",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search by transactionId",
                        "name": "transactionId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/adapter.DataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/services.TransactionDto"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/trade/tradeInCreation": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trade"
                ],
                "summary": "交易藝術品",
                "parameters": [
                    {
                        "description": "藝術品交易資料",
                        "name": "tradeInCreation",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services.TradeInCreationDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/adapter.DataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/services.TransactionDto"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/user/deleteUser": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "刪除會員",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search by userId",
                        "name": "userId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "$ref": "#/definitions/adapter.NonDataResp"
                        }
                    }
                }
            }
        },
        "/api/user/exist": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "查看會員",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search by userId",
                        "name": "userId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by userName",
                        "name": "userName",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/adapter.DataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/user/findUser": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "取的會員資料",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search by userId",
                        "name": "userId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search by userName",
                        "name": "userName",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/adapter.DataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/services.UserDto"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/user/register": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "建立會員",
                "parameters": [
                    {
                        "description": "註冊Dto",
                        "name": "RegisterUser",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services.RegisterUserDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/adapter.DataResp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/services.UserDto"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/user/sayHello": {
            "get": {
                "tags": [
                    "user"
                ],
                "summary": "取的會員資料",
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "$ref": "#/definitions/adapter.NonDataResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "adapter.DataResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "adapter.NonDataResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "services.BrandDto": {
            "type": "object",
            "properties": {
                "brandId": {
                    "type": "string"
                },
                "createAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "imageUrl": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "services.CollectDto": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "creationId": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                }
            }
        },
        "services.CreationDto": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "brandId": {
                    "type": "string"
                },
                "contractAddress": {
                    "type": "string"
                },
                "creationId": {
                    "type": "string"
                },
                "creationName": {
                    "type": "string"
                },
                "creator": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "properties": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "saleEndAt": {
                    "type": "string"
                },
                "saleStartAt": {
                    "type": "string"
                },
                "saleStatus": {
                    "type": "string"
                },
                "saleWay": {
                    "type": "string"
                },
                "smallImageUrl": {
                    "type": "string"
                }
            }
        },
        "services.DeliverItemDto": {
            "type": "object",
            "properties": {
                "contract": {
                    "type": "string"
                },
                "creationId": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "services.ItemDto": {
            "type": "object",
            "properties": {
                "brandOwner": {
                    "type": "string"
                },
                "contract": {
                    "type": "string"
                },
                "creation": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "services.OrderItemDto": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "creationId": {
                    "type": "string"
                }
            }
        },
        "services.PostBrandDto": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "imageUrl": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "services.PostCreationDto": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "brandId": {
                    "type": "string"
                },
                "contractAddress": {
                    "type": "string"
                },
                "creationName": {
                    "type": "string"
                },
                "creator": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "properties": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "saleEndAt": {
                    "type": "string"
                },
                "saleStartAt": {
                    "type": "string"
                },
                "saleStatus": {
                    "type": "string"
                },
                "saleWay": {
                    "type": "string"
                },
                "smallImageUrl": {
                    "type": "string"
                }
            }
        },
        "services.RegisterUserDto": {
            "type": "object",
            "properties": {
                "etherAccount": {
                    "type": "string"
                }
            }
        },
        "services.TradeInCreationDto": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "buyer": {
                    "type": "string"
                },
                "creationId": {
                    "type": "string"
                },
                "seller": {
                    "type": "string"
                }
            }
        },
        "services.TransactionDto": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "brandId": {
                    "type": "string"
                },
                "buyer": {
                    "type": "string"
                },
                "creation": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "seller": {
                    "type": "string"
                },
                "tradeAt": {
                    "type": "string"
                },
                "transactionId": {
                    "type": "string"
                }
            }
        },
        "services.UpdateBrandDto": {
            "type": "object",
            "properties": {
                "brandId": {
                    "type": "string"
                },
                "imageUrl": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "services.UpdateCreationDto": {
            "type": "object",
            "properties": {
                "creationId": {
                    "type": "string"
                },
                "creationName": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "saleEndAt": {
                    "type": "string"
                },
                "saleStartAt": {
                    "type": "string"
                }
            }
        },
        "services.UserDto": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "JWT": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "Swagger API",
	Description: "Swagger API for Golang Project Blueprint.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
